### ISSUE TITLE
 a bug?

### ISSUE THREAD

**Issue by wyzjack** [OPTML-Group/BiP#1]
Hi authors,

Congrats on the nice work. However I am confused with several lines in your code in https://github.com/OPTML-Group/BiP/blob/c51fc350c6c1fde9b6742bdf089153a97d257a16/utils/model.py#L340.
<img width="450" alt="image" src="https://user-images.githubusercontent.com/36599296/230225040-b1af3a07-8b9d-482d-8304-9f9d8f930d46.png">

Here from l.340-342 it seems that the three lines of code will not change the value of "mask" as flatten is not an in-place operation?

Thanks

**Comment by NormalUhr** [comment]
Hi Yizhou, 

thanks for your interest in our work. I just double checked the usage of the `flatten` function. It turns out the variable `flat_out` and `mask` share the same address, which means changing the value of `flat_out` will change `mask`. This can be justified by a small demo showing below. 

![image](https://user-images.githubusercontent.com/50239518/233479726-6250ad33-7515-4357-8985-63dcc77c2dee.png)

Best,

**Comment by wyzjack** [comment]
Great, thanks for your reply and it well solved my issue. 
Congrats again for the nice work!
